vich_uploader:
    db_driver: orm
    metadata:
        type: attribute

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
    mappings:
        face:
            uri_prefix: /file/images/
            upload_destination: '%kernel.project_dir%/public/file/images/'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer